// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ayWrxYzDfJDBMN1IpVqcp8e-HtuiOhk',
    appId: '1:209092871486:web:dc556a3ab5f8c2734f586f',
    messagingSenderId: '209092871486',
    projectId: 'ppb-crud-auth',
    authDomain: 'ppb-crud-auth.firebaseapp.com',
    storageBucket: 'ppb-crud-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVtJrPgVwXH9TWHzVd7kvoMuxp5J0Ckk',
    appId: '1:209092871486:android:d40113ada36b34ba4f586f',
    messagingSenderId: '209092871486',
    projectId: 'ppb-crud-auth',
    storageBucket: 'ppb-crud-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fI82YZ8VU3ChNpoIESe5tOWfKcmcTdg',
    appId: '1:209092871486:ios:df21ba9b285df4314f586f',
    messagingSenderId: '209092871486',
    projectId: 'ppb-crud-auth',
    storageBucket: 'ppb-crud-auth.firebasestorage.app',
    iosBundleId: 'com.example.crudAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fI82YZ8VU3ChNpoIESe5tOWfKcmcTdg',
    appId: '1:209092871486:ios:df21ba9b285df4314f586f',
    messagingSenderId: '209092871486',
    projectId: 'ppb-crud-auth',
    storageBucket: 'ppb-crud-auth.firebasestorage.app',
    iosBundleId: 'com.example.crudAuthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ayWrxYzDfJDBMN1IpVqcp8e-HtuiOhk',
    appId: '1:209092871486:web:1c761a06995c33ea4f586f',
    messagingSenderId: '209092871486',
    projectId: 'ppb-crud-auth',
    authDomain: 'ppb-crud-auth.firebaseapp.com',
    storageBucket: 'ppb-crud-auth.firebasestorage.app',
  );

}